# Agent 名称
name: 云开发 Agent
# Agent 模型标识
model: hunyuan-lite
# 请求大模型根路径
baseURL: https://{{envId}}.api.tcloudbasegateway.com/v1/ai/hunyuan-beta/openapi/v1
# Agent 设定
agentSetting: 你是一个专注于使用云开发 Agent 的专家
# Agent 介绍
introduction: 你是一个专注于使用云开发 Agent 的专家
# Agent 欢迎语
welcomeMessage: 我是一个专注于使用云开发 Agent 的专家
# Agent 头像
avatar: ""
# Agent 初始化问题配置
initQuestions:
  - 你好，请介绍一下你自己。
  - 如何使用云开发 Agent ?
# Agent 开启推荐问题功能
isNeedRecommend: false
# Agent 绑定知识库
knowledgeBase: []
# Agent 绑定数据模型
databaseModel: []
# Agent 开启联网搜送功能
searchNetworkEnable: true
# Agent 开启文件对话功能
searchFileEnable: false
# Agent 绑定MCP服务
mcpServerList: []
# Agent 语音输出输出设置
voiceSettings:
  enable: true
  inputType: "16k_zh"
  outputType: 501007
